### ISSUE TITLE
[BUG] 'Cannot read property '0' of undefined - JammyLogger

### ISSUE THREAD

**Issue by oof2win2** [DistroByte/AwF-Bot#52]
```
0|JammyBot  | TypeError: Cannot read property '0' of undefined
0|JammyBot  |     at Object.parseJammyLogger (/opt/factorio/AwF-Bot-Production/functions.js:481:13)
0|JammyBot  |     at runMicrotasks (<anonymous>)
0|JammyBot  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Not completely sure *when* this happens, but it doesn't seem very good, as it blocks something from happening. This was before #50 was added, so the location is now functions.js:737:13 (`let time = parseInt(line[2]);`). Needs to be investigated more.
EDIT: Seems to be more like functions.js:735 as there it is accessing the 0th element

**Comment by oof2win2** [comment]
Closing bug, as I wasn't able to find it in the logs since 29th December

**Comment by oof2win2** [comment]
Issue found again
